# Use an official PostgreSQL image as a parent image
FROM postgres:13

# Set the working directory in the container
WORKDIR /db

# Copy the initialization script into the container
COPY init.sql /docker-entrypoint-initdb.d/
